### ISSUE TITLE
Not able to get rid of "Couldn't Go to Space!", shortcuts

### ISSUE THREAD

**Issue by bsdooby** [hyperjeff/NameSpace#2]
On macOS Sonoma [latest] I do not quite get how to set shortcuts to switch to namespace (desktop) <name> via the menubar of NameSpace. There's that Warning sign. I set my shortcuts acc. to the hint (btw: it is called System Settings), e.g. CTRL (^) - 1, CTRL (^) - 2, (which corresponds to the default). Assigning some other key combos did not help either...

**Comment by hyperjeff** [comment]
Let's get this working for you. Did your System Settings → Keyboard → Keyboard Shortcuts... → Mission Control → Mission Control also show you a little warning sign next to the short cut you chose? In Sonoma the items are called "Switch to Desktop 1" etc. Do any of them have warning symbols next to them? If so, that'll cause the trouble you describe.

And thanks for the pointer that the location of the items have changed as of Sonoma. I'll have to add some OS-specific text for the help message.

**Comment by bsdooby** [comment]
Hi,

Thank you for your feedback and an update to fix the "wording" acc. to the
macOS version.

I never had warning(s) (signs) in the System Settings;

However, I just restarted the app, and now everything seems to be working...
No warning signs anymore in the Menu Bar.

How come? I don't know...

You can close the issue, but maybe have a look for which situations
(allow/deny
access, hot keys, etc.) this particular issue could occur.

BTW: I like the Space Folder Feature!

Cheers

**Comment by bsdooby** [comment]
Adding a new desktop, and assigning a hotkey requires Spaces to be
restarted to pick it up...

**Comment by hyperjeff** [comment]
ah, great! This all gave me an excuse to fix several little things in the app.

Also, happy to hear that you like the folders!
